package dialogs;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author lucy
 */
public class RefactorSessionDialog extends JDialog {

    private String pass, newSessionName;
    private static final int PASS_MIN_LENGTH = 3, SESSION_NAME_MIN_LENGTH = 5;
    private boolean isCanceled = false;

    public static void main(String[] args) {

        // initializes the main Frame
        JFrame window = new JFrame("accounts and passwords");
        window.setPreferredSize(new Dimension(200, 300));
        //sets the listener to save data on quit
        RefactorSessionDialog d = new RefactorSessionDialog(window);
        System.exit(0);
    }

    /**
     * Creates new form SimpleDialog
     */
    public RefactorSessionDialog(JFrame parent) {
        super(parent, "change session details", true);
        this.setLocationRelativeTo( parent );
        this.setPreferredSize(new Dimension(250, 300));
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        newSessionL = new JLabel();
        newPassL = new JLabel();
        okButton = new JButton();
        cancelButton = new JButton();
        newPassPF = new JPasswordField();
        newSessionTF = new JTextField();
        introTextL = new JLabel();

        setMinimumSize(new Dimension(320, 150));
        setModal(true);
        setResizable(false);

        newSessionL.setText("New session name:");

        newPassL.setText("New password:");

        okButton.setText("OK");
        okButton.setEnabled(false);
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        newPassPF.setToolTipText("minimum " + PASS_MIN_LENGTH + " characters");
        newPassPF.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                newPassPFKeyTyped(evt);
            }
        });

        newSessionTF.setToolTipText("must start with a letter have min 5 characters; contains only letters and digits; Delimiters accepted : _.-");
        newSessionTF.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                newSessionTFKeyTyped(evt);
            }
        });

        introTextL.setText("<HTML><p style=\"text-align:center\">Be careful, " +
                "there is no way to undo these changes!</p>");
        introTextL.setBorder(null);
        introTextL.setRequestFocusEnabled(false);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup( GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(129, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap( LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                            .addComponent(newSessionL)
                            .addComponent(newPassL))
                        .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                            .addComponent(newPassPF)
                            .addComponent(newSessionTF)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(introTextL, GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup( GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(introTextL, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                    .addComponent(newSessionL)
                    .addComponent(newSessionTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                    .addComponent(newPassL)
                    .addComponent(newPassPF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap( LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton)
                    .addGroup( GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addContainerGap())))
        );

        newSessionTF.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>

    private void cancelButtonActionPerformed(ActionEvent evt) {
        this.isCanceled = true;
        this.dispose();
    }                                            

    private void okButtonActionPerformed(ActionEvent evt) {
        this.pass = new String(this.newPassPF.getPassword());
        this.newSessionName = this.newSessionTF.getText();
        if (this.pass.length() < PASS_MIN_LENGTH) {
            this.newPassPF.requestFocus();
            return;
        }

        if (this.newSessionName.length() < 5) {
            this.newPassPF.requestFocus();
            return;
        }

        //reset the form for later use and dispose
        this.reset();
        this.dispose();
    }                                        

    private void newSessionTFKeyTyped(KeyEvent evt) {
       setOkButtonState();
    }

    private void newPassPFKeyTyped(KeyEvent evt) {
        setOkButtonState();
    }

    
    public void setOkButtonState(){
         String s = this.newSessionTF.getText();
        if ((this.newPassPF.getPassword().length > PASS_MIN_LENGTH && s != null && s.matches("^(?i)[a-z][a-z1-9\\._-]{" + (SESSION_NAME_MIN_LENGTH - 1) + ",}$") ) ){
            this.okButton.setEnabled(true);
        }else{
            this.okButton.setEnabled(false);
        }
    }
    
    public void reset() {
        this.newSessionTF.setText("");
        this.newPassPF.setText("");
    }

    public String getPass() {
        return pass;
    }


    public boolean isCanceled(  ) {
        return isCanceled;
    }//end isCanceled

    public String getSessionName() {
        return this.newSessionName;
    }

    // Variables declaration - do not modify
    private JButton cancelButton;
    private JLabel introTextL;
    private JLabel newPassL;
    private JPasswordField newPassPF;
    private JLabel newSessionL;
    private JTextField newSessionTF;
    private JButton okButton;
    // End of variables declaration
}
