package dialogs;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author lucy
 */
public class RefactorSessionDialog extends javax.swing.JDialog {

    private String pass, newSessionName;
    private boolean status = true; //set to false if cancel or close pressed
    private static final int PASS_MIN_LENGTH = 3, SESSION_NAME_MIN_LENGTH = 5;

    public static void main(String[] args) {

        // initializes the main Frame
        JFrame window = new JFrame("accounts and passwords");
        window.setPreferredSize(new Dimension(200, 300));
        //sets the listener to save data on quit
        RefactorSessionDialog d = new RefactorSessionDialog(window);
        System.exit(0);
    }

    /**
     * Creates new form SimpleDialog
     */
    public RefactorSessionDialog(JFrame parent) {
        super(parent, "informations", true);
        this.setPreferredSize(new Dimension(200, 300));
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        newSessionL = new javax.swing.JLabel();
        newPassL = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        newPassPF = new javax.swing.JPasswordField();
        newSessionTF = new javax.swing.JTextField();
        introTextL = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(320, 150));
        setModal(true);
        setResizable(false);

        newSessionL.setText("New session name:");

        newPassL.setText("New password:");

        okButton.setText("OK");
        okButton.setEnabled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        newPassPF.setToolTipText("minimum " + PASS_MIN_LENGTH + " characters");
        newPassPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newPassPFKeyTyped(evt);
            }
        });

        newSessionTF.setToolTipText("must start with a letter have min 5 characters; contains only letters and digits; Delimiters accepted : _.-");
        newSessionTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newSessionTFKeyTyped(evt);
            }
        });

        introTextL.setEditable(false);
        introTextL.setText("Be careful, there is no way to undo these changes.");
        introTextL.setOpaque( false );
        introTextL.setBorder(null);
        introTextL.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(129, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newSessionL)
                            .addComponent(newPassL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPassPF)
                            .addComponent(newSessionTF)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(introTextL, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(introTextL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSessionL)
                    .addComponent(newSessionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPassL)
                    .addComponent(newPassPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addContainerGap())))
        );

        newSessionTF.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        this.status = false;
        this.dispose();
    }                                            

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.pass = new String(this.newPassPF.getPassword());
        this.newSessionName = this.newSessionTF.getText();
        if (this.pass.length() < PASS_MIN_LENGTH) {
            this.newPassPF.requestFocus();
            return;
        }

        if (this.newSessionName.length() < 5) {
            this.newPassPF.requestFocus();
            return;
        }

        //reset the form for later use and dispose
        this.reset();
        this.dispose();
    }                                        

    private void newSessionTFKeyTyped(java.awt.event.KeyEvent evt) {
       setOkButtonState();
    }

    private void newPassPFKeyTyped(java.awt.event.KeyEvent evt) {
        setOkButtonState();
    }

    
    public void setOkButtonState(){
         String s = this.newSessionTF.getText();
        if ((this.newPassPF.getPassword().length > PASS_MIN_LENGTH && s != null && s.matches("^(?i)[a-z][a-z1-9\\._-]{" + (SESSION_NAME_MIN_LENGTH - 1) + ",}$") ) ){
            this.okButton.setEnabled(true);
        }else{
            this.okButton.setEnabled(false);
        }
    }
    
    public void reset() {
        this.newSessionTF.setText("");
        this.newPassPF.setText("");
    }

    public String getPass() {
        return pass;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

    public void setSessionName(String sessionName) {
        this.newSessionName = sessionName;
    }

    public String getSessionName() {
        return this.newSessionName;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }
    // Variables declaration - do not modify
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField introTextL;
    private javax.swing.JLabel newPassL;
    private javax.swing.JPasswordField newPassPF;
    private javax.swing.JLabel newSessionL;
    private javax.swing.JTextField newSessionTF;
    private javax.swing.JButton okButton;
    // End of variables declaration
}
